spring:
  application:
    name: app
  jackson:
    serialization:
      write-dates-as-timestamps: false

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  dsn: ${SENTRY_DSN:}
  send-default-pii: true
  exception-resolver-order: -2147483647
  traces-sample-rate: 1.0